name: Vue CI

on:
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: npx cypress install
      - name: Run Unit Tests
        run: yarn test:unit
      - name: Run e2e Tests
        run: yarn test:e2e
      - name: Run Build
        run: yarn build
